### ISSUE TITLE
EU server not working

### ISSUE THREAD

**Issue by eythork** [nightscout/share2nightscout-bridge#41]
I'm not able to access the dexcom sharing server via shareous2.dexcom.com using a european/EU login account.  shareous1.dexcom.com seems to be working though.

**Comment by bewest** [comment]
Recommend filing support ticket with dexcom so they can track.

**Comment by KoenigAl** [comment]
Actually, this issue took me several hours to fix as all howtos tell us to simply enter "EU" in the BRIDGE_SERVER field if you are using a European Dexcom. Entering "shareous1.dexcom.com" in the field does the trick.
Thus it would be extremely helpful for all European users if you could update your code to use shareous1 instead of 2.

**Comment by bewest** [comment]
Thanks again for your participation.  This should be addressed in previous releases, closing issue.  Please reopen or file a new issue for additional questions.
